import React from 'react'
import { Card, Loader, FormField } from "../components";
import { useState } from 'react';

const RenderCards = ({ data, title }) => {
    if (data?.length > 0) {
        return (
            data.map((post) => <Card key={post._id} {...post} />)
        );
    }

    return (
        <h2 className="mt-5 font-bold text-[#6469ff] text-xl uppercase">{title}</h2>
    );
};


const Home = () => {

    const [loading, setLoading] = useState(false);
    const [allPosts, setAllPosts] = useState(null);
    const [searchText, setSearchText] = useState('');

    return (
        <section className="max-w-7xl mx-auto">
            <div>
                <h1 className="font-extrabold text-[#222328] text-[32px]">The Community Showcase</h1>
                <p className="mt-2 text-[#666e75] text-[14px] max-w-[600px]">Browse through a collection of imaginative and visually stunning images generated by <b>DALL-E AI</b> presented by <b>PALL-E AI</b></p>
            </div>


        </section>
    )

}

export default Home